//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Player.LibraryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SongModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlbumField;
        
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        private int RatingField;
        
        private int DirectoryIDField;
        
        private int TrackNoField;
        
        private bool NowPlayingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Album {
            get {
                return this.AlbumField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumField, value) != true)) {
                    this.AlbumField = value;
                    this.RaisePropertyChanged("Album");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LengthString {
            get {
                return this.LengthStringField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthStringField, value) != true)) {
                    this.LengthStringField = value;
                    this.RaisePropertyChanged("LengthString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int DirectoryID {
            get {
                return this.DirectoryIDField;
            }
            set {
                if ((this.DirectoryIDField.Equals(value) != true)) {
                    this.DirectoryIDField = value;
                    this.RaisePropertyChanged("DirectoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int TrackNo {
            get {
                return this.TrackNoField;
            }
            set {
                if ((this.TrackNoField.Equals(value) != true)) {
                    this.TrackNoField = value;
                    this.RaisePropertyChanged("TrackNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool NowPlaying {
            get {
                return this.NowPlayingField;
            }
            set {
                if ((this.NowPlayingField.Equals(value) != true)) {
                    this.NowPlayingField = value;
                    this.RaisePropertyChanged("NowPlaying");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryServiceReference.ILibraryService")]
    public interface ILibraryService {
        
        // CODEGEN: Generating message contract since element name dummyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/dummy", ReplyAction="http://tempuri.org/ILibraryService/dummyResponse")]
        Music_Player.LibraryServiceReference.dummyResponse dummy(Music_Player.LibraryServiceReference.dummyRequest request);
        
        // CODEGEN: Generating message contract since element name GetSongsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetSongs", ReplyAction="http://tempuri.org/ILibraryService/GetSongsResponse")]
        Music_Player.LibraryServiceReference.GetSongsResponse GetSongs(Music_Player.LibraryServiceReference.GetSongsRequest request);
        
        // CODEGEN: Generating message contract since element name genre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetSongsByGenre", ReplyAction="http://tempuri.org/ILibraryService/GetSongsByGenreResponse")]
        Music_Player.LibraryServiceReference.GetSongsByGenreResponse GetSongsByGenre(Music_Player.LibraryServiceReference.GetSongsByGenreRequest request);
        
        // CODEGEN: Generating message contract since element name album from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetSongsByAlbum", ReplyAction="http://tempuri.org/ILibraryService/GetSongsByAlbumResponse")]
        Music_Player.LibraryServiceReference.GetSongsByAlbumResponse GetSongsByAlbum(Music_Player.LibraryServiceReference.GetSongsByAlbumRequest request);
        
        // CODEGEN: Generating message contract since element name path from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetSongStream", ReplyAction="http://tempuri.org/ILibraryService/GetSongStreamResponse")]
        Music_Player.LibraryServiceReference.GetSongStreamResponse GetSongStream(Music_Player.LibraryServiceReference.GetSongStreamRequest request);
        
        // CODEGEN: Generating message contract since element name path from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetAlbumArtStream", ReplyAction="http://tempuri.org/ILibraryService/GetAlbumArtStreamResponse")]
        Music_Player.LibraryServiceReference.GetAlbumArtStreamResponse GetAlbumArtStream(Music_Player.LibraryServiceReference.GetAlbumArtStreamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dummyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dummy", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.dummyRequestBody Body;
        
        public dummyRequest() {
        }
        
        public dummyRequest(Music_Player.LibraryServiceReference.dummyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dummyRequestBody {
        
        public dummyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dummyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dummyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.dummyResponseBody Body;
        
        public dummyResponse() {
        }
        
        public dummyResponse(Music_Player.LibraryServiceReference.dummyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dummyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dummyResult;
        
        public dummyResponseBody() {
        }
        
        public dummyResponseBody(string dummyResult) {
            this.dummyResult = dummyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongs", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongsRequestBody Body;
        
        public GetSongsRequest() {
        }
        
        public GetSongsRequest(Music_Player.LibraryServiceReference.GetSongsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSongsRequestBody {
        
        public GetSongsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongsResponseBody Body;
        
        public GetSongsResponse() {
        }
        
        public GetSongsResponse(Music_Player.LibraryServiceReference.GetSongsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSongsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsResult;
        
        public GetSongsResponseBody() {
        }
        
        public GetSongsResponseBody(System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsResult) {
            this.GetSongsResult = GetSongsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongsByGenreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongsByGenre", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongsByGenreRequestBody Body;
        
        public GetSongsByGenreRequest() {
        }
        
        public GetSongsByGenreRequest(Music_Player.LibraryServiceReference.GetSongsByGenreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSongsByGenreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string genre;
        
        public GetSongsByGenreRequestBody() {
        }
        
        public GetSongsByGenreRequestBody(string genre) {
            this.genre = genre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongsByGenreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongsByGenreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongsByGenreResponseBody Body;
        
        public GetSongsByGenreResponse() {
        }
        
        public GetSongsByGenreResponse(Music_Player.LibraryServiceReference.GetSongsByGenreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSongsByGenreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsByGenreResult;
        
        public GetSongsByGenreResponseBody() {
        }
        
        public GetSongsByGenreResponseBody(System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsByGenreResult) {
            this.GetSongsByGenreResult = GetSongsByGenreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongsByAlbumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongsByAlbum", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongsByAlbumRequestBody Body;
        
        public GetSongsByAlbumRequest() {
        }
        
        public GetSongsByAlbumRequest(Music_Player.LibraryServiceReference.GetSongsByAlbumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSongsByAlbumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string album;
        
        public GetSongsByAlbumRequestBody() {
        }
        
        public GetSongsByAlbumRequestBody(string album) {
            this.album = album;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongsByAlbumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongsByAlbumResponse", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongsByAlbumResponseBody Body;
        
        public GetSongsByAlbumResponse() {
        }
        
        public GetSongsByAlbumResponse(Music_Player.LibraryServiceReference.GetSongsByAlbumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSongsByAlbumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsByAlbumResult;
        
        public GetSongsByAlbumResponseBody() {
        }
        
        public GetSongsByAlbumResponseBody(System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsByAlbumResult) {
            this.GetSongsByAlbumResult = GetSongsByAlbumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongStream", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongStreamRequestBody Body;
        
        public GetSongStreamRequest() {
        }
        
        public GetSongStreamRequest(Music_Player.LibraryServiceReference.GetSongStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSongStreamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float offsetPercentage;
        
        public GetSongStreamRequestBody() {
        }
        
        public GetSongStreamRequestBody(string path, float offsetPercentage) {
            this.path = path;
            this.offsetPercentage = offsetPercentage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSongStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSongStreamResponse", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetSongStreamResponseBody Body;
        
        public GetSongStreamResponse() {
        }
        
        public GetSongStreamResponse(Music_Player.LibraryServiceReference.GetSongStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSongStreamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] GetSongStreamResult;
        
        public GetSongStreamResponseBody() {
        }
        
        public GetSongStreamResponseBody(byte[] GetSongStreamResult) {
            this.GetSongStreamResult = GetSongStreamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlbumArtStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlbumArtStream", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetAlbumArtStreamRequestBody Body;
        
        public GetAlbumArtStreamRequest() {
        }
        
        public GetAlbumArtStreamRequest(Music_Player.LibraryServiceReference.GetAlbumArtStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlbumArtStreamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public GetAlbumArtStreamRequestBody() {
        }
        
        public GetAlbumArtStreamRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlbumArtStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlbumArtStreamResponse", Namespace="http://tempuri.org/", Order=0)]
        public Music_Player.LibraryServiceReference.GetAlbumArtStreamResponseBody Body;
        
        public GetAlbumArtStreamResponse() {
        }
        
        public GetAlbumArtStreamResponse(Music_Player.LibraryServiceReference.GetAlbumArtStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlbumArtStreamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] GetAlbumArtStreamResult;
        
        public GetAlbumArtStreamResponseBody() {
        }
        
        public GetAlbumArtStreamResponseBody(byte[] GetAlbumArtStreamResult) {
            this.GetAlbumArtStreamResult = GetAlbumArtStreamResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryServiceChannel : Music_Player.LibraryServiceReference.ILibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryServiceClient : System.ServiceModel.ClientBase<Music_Player.LibraryServiceReference.ILibraryService>, Music_Player.LibraryServiceReference.ILibraryService {
        
        public LibraryServiceClient() {
        }
        
        public LibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Music_Player.LibraryServiceReference.dummyResponse Music_Player.LibraryServiceReference.ILibraryService.dummy(Music_Player.LibraryServiceReference.dummyRequest request) {
            return base.Channel.dummy(request);
        }
        
        public string dummy() {
            Music_Player.LibraryServiceReference.dummyRequest inValue = new Music_Player.LibraryServiceReference.dummyRequest();
            inValue.Body = new Music_Player.LibraryServiceReference.dummyRequestBody();
            Music_Player.LibraryServiceReference.dummyResponse retVal = ((Music_Player.LibraryServiceReference.ILibraryService)(this)).dummy(inValue);
            return retVal.Body.dummyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Music_Player.LibraryServiceReference.GetSongsResponse Music_Player.LibraryServiceReference.ILibraryService.GetSongs(Music_Player.LibraryServiceReference.GetSongsRequest request) {
            return base.Channel.GetSongs(request);
        }
        
        public System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongs() {
            Music_Player.LibraryServiceReference.GetSongsRequest inValue = new Music_Player.LibraryServiceReference.GetSongsRequest();
            inValue.Body = new Music_Player.LibraryServiceReference.GetSongsRequestBody();
            Music_Player.LibraryServiceReference.GetSongsResponse retVal = ((Music_Player.LibraryServiceReference.ILibraryService)(this)).GetSongs(inValue);
            return retVal.Body.GetSongsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Music_Player.LibraryServiceReference.GetSongsByGenreResponse Music_Player.LibraryServiceReference.ILibraryService.GetSongsByGenre(Music_Player.LibraryServiceReference.GetSongsByGenreRequest request) {
            return base.Channel.GetSongsByGenre(request);
        }
        
        public System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsByGenre(string genre) {
            Music_Player.LibraryServiceReference.GetSongsByGenreRequest inValue = new Music_Player.LibraryServiceReference.GetSongsByGenreRequest();
            inValue.Body = new Music_Player.LibraryServiceReference.GetSongsByGenreRequestBody();
            inValue.Body.genre = genre;
            Music_Player.LibraryServiceReference.GetSongsByGenreResponse retVal = ((Music_Player.LibraryServiceReference.ILibraryService)(this)).GetSongsByGenre(inValue);
            return retVal.Body.GetSongsByGenreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Music_Player.LibraryServiceReference.GetSongsByAlbumResponse Music_Player.LibraryServiceReference.ILibraryService.GetSongsByAlbum(Music_Player.LibraryServiceReference.GetSongsByAlbumRequest request) {
            return base.Channel.GetSongsByAlbum(request);
        }
        
        public System.Collections.Generic.List<Music_Player.LibraryServiceReference.SongModel> GetSongsByAlbum(string album) {
            Music_Player.LibraryServiceReference.GetSongsByAlbumRequest inValue = new Music_Player.LibraryServiceReference.GetSongsByAlbumRequest();
            inValue.Body = new Music_Player.LibraryServiceReference.GetSongsByAlbumRequestBody();
            inValue.Body.album = album;
            Music_Player.LibraryServiceReference.GetSongsByAlbumResponse retVal = ((Music_Player.LibraryServiceReference.ILibraryService)(this)).GetSongsByAlbum(inValue);
            return retVal.Body.GetSongsByAlbumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Music_Player.LibraryServiceReference.GetSongStreamResponse Music_Player.LibraryServiceReference.ILibraryService.GetSongStream(Music_Player.LibraryServiceReference.GetSongStreamRequest request) {
            return base.Channel.GetSongStream(request);
        }
        
        public byte[] GetSongStream(string path, float offsetPercentage) {
            Music_Player.LibraryServiceReference.GetSongStreamRequest inValue = new Music_Player.LibraryServiceReference.GetSongStreamRequest();
            inValue.Body = new Music_Player.LibraryServiceReference.GetSongStreamRequestBody();
            inValue.Body.path = path;
            inValue.Body.offsetPercentage = offsetPercentage;
            Music_Player.LibraryServiceReference.GetSongStreamResponse retVal = ((Music_Player.LibraryServiceReference.ILibraryService)(this)).GetSongStream(inValue);
            return retVal.Body.GetSongStreamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Music_Player.LibraryServiceReference.GetAlbumArtStreamResponse Music_Player.LibraryServiceReference.ILibraryService.GetAlbumArtStream(Music_Player.LibraryServiceReference.GetAlbumArtStreamRequest request) {
            return base.Channel.GetAlbumArtStream(request);
        }
        
        public byte[] GetAlbumArtStream(string path) {
            Music_Player.LibraryServiceReference.GetAlbumArtStreamRequest inValue = new Music_Player.LibraryServiceReference.GetAlbumArtStreamRequest();
            inValue.Body = new Music_Player.LibraryServiceReference.GetAlbumArtStreamRequestBody();
            inValue.Body.path = path;
            Music_Player.LibraryServiceReference.GetAlbumArtStreamResponse retVal = ((Music_Player.LibraryServiceReference.ILibraryService)(this)).GetAlbumArtStream(inValue);
            return retVal.Body.GetAlbumArtStreamResult;
        }
    }
}
